dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python src/breadth_first_search.py src/maps
  - python src/depth_first_search.py src/maps
  - python src/iterative_deepening_search.py src/maps
